config/routes.rb
Rails.application.routes.draw do
  root "challenges#index"
  resources :challenges
  devise_for :users
  resources :users, only: [:index]
  resources :friendships, only:[:index, :create, :destroy, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :competitors, only: [:create, :destroy]
  resources :user_challenge_details
end

app/models/user_challenge_detail.rb
class UserChallengeDetail < ApplicationRecord
  belongs_to :competitor
end

app/controllers/user_challenge_details_controller.rb
class UserChallengeDetailsController < ApplicationController

  def create
    @user_details = UserChallengeDetail.new(user_challenge_details_params)
    @challenge = @user_details.competitor.challenge_id
    if @user_details.save
      flash.now[:success] = "Added successfully"
      redirect_to challenge_path(@challenge)
    else
      flash.now[:danger] = "Something went wrong"
      redirect_to challenge_path(@challenge)
    end
  end
  
  private
    def user_challenge_details_params
      params.require(:user_challenge_detail).permit(:competitor_id, :detail)
    end

end

app/controllers/users/user_challenge_details.rb
class UserChallengeDetailsController < ApplicationController

  def create
    @challenge = Challenge.find(params[:challenge])
    @user_challenge_detail = @challenge.user_challenge_details.build(user_id: current_user, detail: params[:detail])
    if @user_challenge_detail.save
      flash[:success] = "Successfully added the detail"
      redirect_to challenge_path(@challenge)
    else
      flash[:danger] = "Couldn't add the detail"
      redirect_to challenge_path(@chllenge)
    end
  end


end

app/views/user_challenge_details/_user_details.html.erb
 <div class="table-responsive">
  <table class="table table-hover">
   <thead>
      <tr>
        <th>Entry Date Time</th>
        <th>Entry</th>
        <th>Actions</th>
      </tr>
    </thead>
   <tbody>
      <% @competitor_details.each do |details| %>
        <tr>
          <td><%= details.created_at %></td>
          <td><%= details.detail %></td>
          <td><%= link_to 'Show', details, class:"btn-sm btn-info" %></td>
          <td>
          <% if details.competitor.user_id == current_user %>
            <%= link_to "Edit", edit_user_challenge_details_path(details), class:"btn-sm btn-primary" %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>  
  </table>
</div>