config/routes.rb
Rails.application.routes.draw do
  root "challenges#index"
  resources :challenges
  devise_for :users
  resources :users, only: [:index]
  resources :friendships, only:[:index, :create, :destroy, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :competitors, only: [:create, :destroy]
  resources :user_challenge_details
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :user
  has_many :competitors, dependent: :destroy
  

  validates :title, presence: true, length: {minimum: 3, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 256}
  validates :goal, numericality: { greater_than: 0, less_than: 1000 }
  validates :active, inclusion: {in: [true, false] }
  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  private
  
  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: %i[ show edit update destroy ]

  # GET /challenges or /challenges.json
  def index
    @challenges = Challenge.all
  end

  # GET /challenges/1 or /challenges/1.json
  def show
    competitor = Competitor.find_by(challenge_id: @challenge.id, user_id: current_user)
    @competitor_details = competitor.user_challenge_details.all
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges or /challenges.json
  def create
    @challenge = current_user.challenges.build(challenge_params)

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: "Challenge was successfully created." }
        format.json { render :show, status: :created, location: @challenge }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1 or /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: "Challenge was successfully updated." }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1 or /challenges/1.json
  def destroy
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url, notice: "Challenge was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def challenge_params
      params.require(:challenge).permit(:user_id, :title, :description, :start_date, :end_date, :active, :goal)
    end
end

app/helpers/challenges_helper.rb
module ChallengesHelper


end

app/views/challenges/_form.html.erb
<%= render 'shared/errors', obj: @challenge %>
<div class="card-body">
    <%= form_with(model: challenge, local: true) do |form| %>
    <div class="form-horizontal">
    
      <div class="form-group row">
        <%= form.label :title , class:"col-sm-2 form-control-label" %>
        <%= form.text_field :title, class:"col-sm-10", required: true %>
      </div>

      <div class="form-group row">
        <%= form.label :description , class:"col-sm-2 form-control-label" %>
        <%= form.text_area :description, class:"col-sm-10", required: true %>
      </div>
      <div class="form-group row">
        <%= form.label :start_date , class:"col-sm-2 form-control-label" %>
        <%= form.datetime_select :start_date, class:"col-sm-10" %>
      </div>
      <div class="form-group row">
        <%= form.label :end_date , class:"col-sm-2 form-control-label" %>
        <%= form.datetime_select :end_date, class:"col-sm-10" %>
      </div>
      <div class="form-group row">
        <%= form.label :goal , class:"col-sm-2 form-control-label"  %>
        <%= form.number_field :goal, in: 1.00..999.00, step: 0.1 , class:"col-sm-10"%>
      </div>
      <div class="form-group row">
        <%= form.label :active , class:"col-sm-2 form-control-label" %>
        <%= form.select(:active, [["True", true], ["False", false]], class:"col-sm-10 mb-3") %>
      </div>
      <div class="form-group row">
        <%= form.submit class:"col-sm-10 offset-sm-2 btn btn-primary" %>
      </div>

    </div>

  <% end %>
  
  </div>

</div>

app/views/challenges/edit.html.erb
<div class="card-header d-flex align-items-center">
  <h4>Edit <%= @challenge.title %></h4>
</div>
<div class="card">
  <%= render 'form', challenge: @challenge %>

  <%= link_to 'Show', @challenge %> |
  <%= link_to 'Back', challenges_path %>
</div>

app/views/challenges/index.html.erb
<div class="container">
  <h1 align="center">Showing all challenges</h1>
</div>

<div class="table-responsive">
  <table class="table table-hover">
  <div class="d-flex justify-content-center">
    <%= link_to 'Add New Challenge', new_challenge_path, class:"btn-sm btn-primary justify-content-center" %>
  </div>
    <thead>
      <tr>
        <th>Creator</th>
        <th>Title</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @challenges.each do |challenge| %>
        <tr>
          <td><%= challenge.user_id %></td>
          <td><%= challenge.title %></td>
          <td><%= link_to 'Show', challenge, class:"btn-sm btn-info" %></td>
          <td><% if challenge.user == current_user %>
            <%= link_to "Edit", challenge_path(challenge), class:"btn-sm btn-primary" %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/challenges/new.html.erb
<div class="card-header d-flex align-items-center">
  <h4>Create New Challenge</h4>
</div>
<div class="card">
  <%= render 'form', challenge: @challenge %>

  <%= link_to 'Back', challenges_path %>
</div>

app/views/challenges/show.html.erb
<div class="card">
  <div class="card-header">
    <%= @challenge.title %>
  </div>
  <div class="card-body">
    <div class="card-subtitle">
      <%= @challenge.user.email %>  
    </div>
    <div class="card-text">
      <%= @challenge.description %> 
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Goal: <%= @challenge.goal %></li>
      <li class="list-group-item">Start Date: <%= @challenge.start_date %></li>
      <li class="list-group-item">End Date: <%= @challenge.end_date %></li>
      <li class="list-group-item">Active: <%= @challenge.active %></li>
    </ul>
  </div>
  <div class="card-footer">
    <%= link_to 'Edit', edit_challenge_path(@challenge), class:"btn-sm btn-success" %> | 
    <%= link_to 'Delete', challenge_path(@challenge), method: :delete, class:"btn-sm btn-danger" %>|
    <%= link_to 'Back', challenges_path, class:"btn-sm btn-dark" %>
  </div>
  <div class="card-footer">
    <% if challenge_competitor?(@challenge.id, current_user) %>
      <%= link_to "Join Challenge", competitors_path(challenge: @challenge), class: "btn-sm btn-info", method: :post %>
    <% else %>
      <%= link_to "Leave Challenge", competitor_path(challenge: @challenge, user: current_user), method: :delete, class:"btn-sm btn-danger" %>
  <% end %>
  </div>
</div>

<% if !challenge_competitor?(@challenge.id, current_user) %>
  <div class="d-flex justify-content-center">
      <%= form_for(:user_challenge_detail, url: user_challenge_details_path) do |f| %>
        <%= f.hidden_field :competitor_id, value: challenge_competitor(@challenge.id, current_user).id %>
        <div class="form_group row">
          <div class="col-form-label col-sm-3">
            <%= f.label :detail %>
          </div>
          <div class="col-sm-4">
            <%= f.number_field :detail, step: 0.1, class: "form-control", autofocus: true %>
          </div>
          <%= f.submit "Add", class:"btn-sm btn-primary" %>
        </div>
      <% end %>
    </div>
<% end %>
<%= render 'user_challenge_details/user_details' %>