config/routes.rb
Rails.application.routes.draw do
  root "challenges#index"
  resources :challenges
  devise_for :users
  resources :users, only: [:index]
  resources :friendships, only:[:index, :create, :destroy, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :competitors, only: [:create, :destroy]
  resources :user_challenge_details
end

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-sm-12 col-sm-offset-3">
    <% flash.each do |name, msg| %>
      <% if "#{name}"=="alert" %> 
        <% name = "danger"%>
      <% else %>
        <% name = "success" %>
      <% end %>
      <div class='alert alert-<%= "#{name}" %>' role="alert">
        <a href="#" class="close" data-dismiss="alert">x</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="side-navbar">
<div class="side-navbar-wrapper">
  <!-- Sidebar Header    -->
  <div class="sidenav-header d-flex align-items-center justify-content-center">
    <!-- User Info-->
    <div class="sidenav-header-inner text-center">
      <%= link_to root_path do %>
        <%= image_tag "challenge.jpeg", class:"img-fluid rounded-circle" %>
      <% end %>
      <h2 class="h5">CHALLENGE APPLICATION</h2><span>Challenge your friends</span>
    </div>
    <!-- Small Brand information, appears on minimized sidebar-->
    <div class="sidenav-header-logo"><a href="index.html" class="brand-small text-center"> <strong>B</strong><strong class="text-primary">D</strong></a></div>
  </div>
  <!-- Sidebar Navigation Menus-->
  <div class="main-menu">
    <h5 class="sidenav-heading">Main</h5>
    <ul id="side-main-menu" class="side-menu list-unstyled">                  
      <li><%= link_to root_path do %><i class="fa fa-home"></i> Home<% end %></li>
      <li><%= link_to challenges_path do %><i class="fas fa-cubes"></i> Challenges<% end %></li>
      <li><%= link_to users_path do %><i class="fas fa-users"></i> Users<% end %></li>
      <li><%= link_to "#" do %><i class="fa fa-table"></i> Tables <% end %></li>
      <li><a href="#exampledropdownDropdown" aria-expanded="false" data-toggle="collapse"> <i class="icon-interface-windows"></i>Example dropdown </a>
        <ul id="exampledropdownDropdown" class="collapse list-unstyled ">
          <li><a href="#">Page</a></li>
          <li><a href="#">Page</a></li>
          <li><a href="#">Page</a></li>
        </ul>
      </li>
      <li><a href="#"> <i class="fa fa-window-restore"></i>Login page</a></li>
      <li> <a href="#"> <i class="fas fa-envelope-square"></i>Demo
          <div class="badge badge-warning">6 New</div></a></li>
    </ul>
  </div>
  <div class="admin-menu">
    <h5 class="sidenav-heading">Second menu</h5>
    <ul id="side-admin-menu" class="side-menu list-unstyled"> 
      <li> <a href="#"> <i class="fas fa-tablet-alt"></i>Demo</a></li>
      <li> <a href="#"> <i class="fas fa-flask"></i>Demo
          <div class="badge badge-info">Special</div></a></li>
      <li> <a href=""> <i class="fas fa-flask"></i>Demo</a></li>
      <li> <a href=""> <i class="far fa-image"></i>Demo</a></li>
    </ul>
  </div>
</div>
</nav>
<div class="page">
<!-- navbar-->
<header class="header">
  <nav class="navbar">
    <div class="container-fluid">
      <div class="navbar-holder d-flex align-items-center justify-content-between">
        <div class="navbar-header"><a id="toggle-btn" href="#" class="menu-btn"><i class="icon-bars"> </i></a><a href="index.html" class="navbar-brand">
            <div class="brand-text d-none d-md-inline-block"><span>Bootstrap </span><strong class="text-primary">Dashboard</strong></div></a></div>
        <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
          <!-- Notifications dropdown-->
          <li class="nav-item dropdown"> <a id="notifications" rel="nofollow" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link"><i class="fa fa-bell"></i><span class="badge badge-warning">12</span></a>
            <ul aria-labelledby="notifications" class="dropdown-menu">
              <li><a rel="nofollow" href="#" class="dropdown-item"> 
                  <div class="notification d-flex justify-content-between">
                    <div class="notification-content"><i class="fa fa-envelope"></i>You have 6 new messages </div>
                    <div class="notification-time"><small>4 minutes ago</small></div>
                  </div></a></li>
              <li><a rel="nofollow" href="#" class="dropdown-item"> 
                  <div class="notification d-flex justify-content-between">
                    <div class="notification-content"><i class="fa fa-twitter"></i>You have 2 followers</div>
                    <div class="notification-time"><small>4 minutes ago</small></div>
                  </div></a></li>
              <li><a rel="nofollow" href="#" class="dropdown-item"> 
                  <div class="notification d-flex justify-content-between">
                    <div class="notification-content"><i class="fa fa-upload"></i>Server Rebooted</div>
                    <div class="notification-time"><small>4 minutes ago</small></div>
                  </div></a></li>
              <li><a rel="nofollow" href="#" class="dropdown-item"> 
                  <div class="notification d-flex justify-content-between">
                    <div class="notification-content"><i class="fa fa-twitter"></i>You have 2 followers</div>
                    <div class="notification-time"><small>10 minutes ago</small></div>
                  </div></a></li>
              <li><a rel="nofollow" href="#" class="dropdown-item all-notifications text-center"> <strong> <i class="fa fa-bell"></i>view all notifications                                            </strong></a></li>
            </ul>
          </li>
          <!-- Messages dropdown-->
          <li class="nav-item dropdown"> <a id="messages" rel="nofollow" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link"><i class="fa fa-envelope"></i><span class="badge badge-info">10</span></a>
            <ul aria-labelledby="notifications" class="dropdown-menu">
              <li><a rel="nofollow" href="#" class="dropdown-item d-flex"> 
                  <div class="msg-profile"> <img src="#" alt="..." class="img-fluid rounded-circle"></div>
                  <div class="msg-body">
                    <h3 class="h5">Jason Doe</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2014</small>
                  </div></a></li>
              <li><a rel="nofollow" href="#" class="dropdown-item d-flex"> 
                  <div class="msg-profile"> <img src="#" alt="..." class="img-fluid rounded-circle"></div>
                  <div class="msg-body">
                    <h3 class="h5">Frank Williams</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2014</small>
                  </div></a></li>
              <li><a rel="nofollow" href="#" class="dropdown-item d-flex"> 
                  <div class="msg-profile"> <img src="#" alt="..." class="img-fluid rounded-circle"></div>
                  <div class="msg-body">
                    <h3 class="h5">Ashley Wood</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2014</small>
                  </div></a></li>
              <li><a rel="nofollow" href="#" class="dropdown-item all-notifications text-center"> <strong> <i class="fa fa-envelope"></i>Read all messages    </strong></a></li>
            </ul>
          </li>
          <!-- Log out-->
          <li class="nav-item">
          <% if signed_in? %>
            <%= link_to destroy_user_session_path, class:"nav-link logout", method: :delete  do %>
              <i class="fa fa-sign-out-alt"></i>Logout
            <% end %>
          <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>
<footer class="main-footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6">
        <p>Your company &copy; 2017-2020</p>
      </div>
      <div class="col-sm-6 text-right">
        <p>Design by <a href="https://bootstrapious.com/p/bootstrap-4-dashboard" class="external">Bootstrapious</a></p>
        <!-- Please do not remove the backlink to us unless you support further theme's development at https://bootstrapious.com/donate. It is part of the license conditions and it helps me to run Bootstrapious. Thank you for understanding :)-->
      </div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChallengeApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <div class="container-fluid">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
  </body>
</html>